spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        enabled: true #启用服务发现
        register: true #启用服务注册
        deregister: true #服务停止时取消注册
        healthCheckPath: /actuator/health #健康检查的路径
        healthCheckInterval: 10s #执行监控检查的频率
        serviceName: consul-service-consumer
log:
  path: /logs
  proName: springboot
  rootLevel: info # info debug